#!/bin/sh
# File generated by ocamlbuild

cd /home/olivier/Documents/University/H-16/Compiler/GOcaml/src

rm -f ast.cmi
rm -f ast.cmo
rm -f lex.ml
rm -f parser.ml
rm -f parser.mli
# Also clean the script itself
rm -f /home/olivier/Documents/University/H-16/Compiler/GOcaml/src/_build/sanitize.sh
