#!/bin/sh
# File generated by ocamlbuild

cd '/Users/terrenceko/Dropbox/McGill Winter 2016/Comp 520/GOcaml/src'

rm -f lex.ml
rm -f parser.ml
rm -f parser.mli
# Also clean the script itself
rm -f '/Users/terrenceko/Dropbox/McGill Winter 2016/Comp 520/GOcaml/src/_build/sanitize.sh'
